import json
import os
from datetime import datetime

"""move_files() opens the JSON files generated by albatross.py and moves the 
   files within to their respective folders.
"""

types = ['Images', 'Videos', 'Documents',
         'Archives', 'Diskimages', 'Audio', 'Apps']


def move_files():
    for type0 in types:
        jsonfile = open(f'{type0}.json')
        dict = json.load(jsonfile)
        dir = f"./{type0}"
        try:
            os.mkdir(dir)
        except (FileExistsError):
            pass
        if type0 == 'Images':
            for v in dict.values():
                subdir = f"./{type0}/{v['Date']}"
                filename = os.path.basename(v['Path'])
                try:
                    os.mkdir(subdir)
                except FileExistsError:
                    pass
                move = f"{v['Path']} {subdir}/{filename}"
               # os.system(move)
                print(move)
            else:
                for v in dict.values():
                    filename = os.path.basename(v['Path'])
                    move2 = f"{v['Path']} {subdir}/{filename}"
                    print(move2)


move_files()
